# Generated by Django 4.2.5 on 2024-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='type',
            field=models.CharField(choices=[('new', 'добавил новость'), ('friend', 'добавил друга'), ('photo', 'добавил фото')], max_length=30, unique=True, verbose_name='Тип'),
        ),
    ]
