# Generated by Django 4.2.5 on 2024-02-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="unique_name_slug_together"
            ),
        ),
    ]
