# Generated by Django 4.2.5 on 2024-02-29 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0002_city_unique_name_slug_together"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="city",
            name="unique_name_slug_together",
        ),
    ]
