# Generated by Django 4.2.5 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_like_new_alter_like_user_commentlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='n/n/i', verbose_name='Фото'),
        ),
    ]
