# Generated by Django 4.2.5 on 2024-01-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities", "0001_initial"),
        ("users", "0002_user_age_user_birth_date_user_city_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="cities.city",
                verbose_name="Город",
            ),
        ),
    ]
