# Generated by Django 4.2.5 on 2024-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_city'),
        ('users', '0003_photo'),
    ]

    operations = [
    ]
