# Generated by Django 4.2.5 on 2024-01-30 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_languages"),
        ("users", "0004_merge_0003_alter_user_city_0003_photo"),
    ]

    operations = []
