# Generated by Django 4.2.5 on 2024-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_news"),
        ("users", "0005_merge_20240130_1757"),
    ]

    operations = []
