# Generated by Django 4.2.5 on 2024-02-01 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                related_name="user_friends", to=settings.AUTH_USER_MODEL, verbose_name="Друзья"
            ),
        ),
    ]
