# Generated by Django 4.2.5 on 2024-02-01 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_friends",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Друзья",
            ),
        ),
    ]
