# Generated by Django 4.2.5 on 2024-02-06 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_friends"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
