# Generated by Django 4.2.5 on 2024-02-15 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_music_alter_photo_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="u/m/f",
                validators=[django.core.validators.FileExtensionValidator(("mp3",))],
                verbose_name="Файл",
            ),
        ),
    ]
