# Generated by Django 4.2.5 on 2024-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_music_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="music",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.music", verbose_name="Моя музыка"
            ),
        ),
    ]
